package com.ko.cds.pojo.csr;

import java.io.Serializable;
import java.math.BigInteger;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.ko.cds.utils.CustomUTCDateSerializer;

/**
 * This class is used to populate CSR ticket details.
 * @author ibm
 *
 */
public class CSRTicket implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -7407688915723992466L;
	/** Unique Id for the member generated by CDS */
	private BigInteger memberId;
	/** The Ko member’s Ko ID */
	private String koMemberKoId;
	/** The KO team member’s name*/
	private String koMemberName;
	/** The data type of the transaction (Example: member profile) – No referential integrity */
	private String dataType;
	/** The reason for the ticket (Example: upated email address) - No referential integrity */
	private String csrReasonCode;
	/** The time of the transaction */
	@JsonSerialize(using = CustomUTCDateSerializer.class)
	private String timestamp;
	
	public BigInteger getMemberId() {
		return memberId;
	}

	public void setMemberId(BigInteger memberId) {
		this.memberId = memberId;
	}

	public String getKoMemberKoId() {
		return koMemberKoId;
	}

	public void setKoMemberKoId(String koMemberKoId) {
		this.koMemberKoId = koMemberKoId;
	}

	public String getKoMemberName() {
		return koMemberName;
	}

	public void setKoMemberName(String koMemberName) {
		this.koMemberName = koMemberName;
	}

	public String getDataType() {
		return dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	public String getCsrReasonCode() {
		return csrReasonCode;
	}

	public void setCsrReasonCode(String csrReasonCode) {
		this.csrReasonCode = csrReasonCode;
	}
	 
}
