package com.ko.cds.request.csr;

import java.io.Serializable;
import java.math.BigInteger;

import javax.ws.rs.QueryParam;

import net.sf.oval.constraint.MaxLength;

import org.codehaus.jackson.map.annotate.JsonDeserialize;

import com.ko.cds.pojo.activity.TagObject;
import com.ko.cds.utils.CustomDateDeserializer;
/***
 * This class is used to map input JSON for
 * Advance Search API to POJO
 * @author ibm
 *
 */
public class CSRAdvanceSearchRequest implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 4137752869782861419L;
	@QueryParam("sessionUUID")
	/** The unique session ID */
	@MaxLength(value=36)
	private String sessionUUID;
	/**Unique Id for the member generated by CDS*/
	@QueryParam("memberId")
	private BigInteger memberId;
	
	@QueryParam("firstName")
	@MaxLength(value=50)
	/**First name of the member (wildcard)*/
	private String firstName;
	
	@QueryParam("lastName")
	@MaxLength(value=50)
	/**Last name of a member (wildcard)*/
	private String lastName;
	
	@QueryParam("address")
	@MaxLength(value=50)
	/**Address of the member*/
	private String address;
	
	@QueryParam("city")
	@MaxLength(value=50)
	/**The town in question*/
	private String city;
	
	@QueryParam("state")
	@MaxLength(value=2)
	/**The town in question*/
	private String state;
	
	@QueryParam("zip")
	@MaxLength(value=15)
	/**The zip code for the specific address*/
	private String zip;
	
	@QueryParam("email")
	@MaxLength(value=100)
	/**The email address being searched  (wild card)*/
	private String email;
	
	@QueryParam("displayName")
	@MaxLength(value=50)
	/**The display name of the individual*/
	private String displayName;
	
	@QueryParam("mobile")
	@MaxLength(value=12)
	/**Search by the SMS number*/
	
	private String mobile;
	/**Search by external ID at janrain – data stored in CDS member idenfier table, it will be 
	 * populated from service class
	 * */
	private TagObject memberIdentifier;
	
	@QueryParam("birthDate")
	@JsonDeserialize(using=CustomDateDeserializer.class)
	/**The date of the birth*/
	private String birthDate;
	
	@QueryParam("createdDate")
	@JsonDeserialize(using=CustomDateDeserializer.class)
	/**The date the member was created */
	private String createdDate;
	
	@QueryParam("janrainUUID")
	@MaxLength(value=36)
	/**The Janrain UUID search*/
	private String janrainUUID;
	
	@QueryParam("houseHoldId")
	/**Search by household*/
	@MaxLength(value=25)
	private String houseHoldId;
	
	
	/**Goes against the member profile table (domain and domain login), it will be populated
	 * from service class
	 * */
	private TagObject socialDomain;
	
	@QueryParam("janrainAccountStatus")
	@MaxLength(value=10)
	/**Janrain Account Status*/
	private String janrainAccountStatus;
	public String getSessionUUID() {
		return sessionUUID;
	}
	public void setSessionUUID(String sessionUUID) {
		this.sessionUUID = sessionUUID;
	}
	public BigInteger getMemberId() {
		return memberId;
	}
	public void setMemberId(BigInteger memberId) {
		this.memberId = memberId;
	}
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	
	public String getCity() {
		return city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public String getZip() {
		return zip;
	}
	public void setZip(String zip) {
		this.zip = zip;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getDisplayName() {
		return displayName;
	}
	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}
	public String getMobile() {
		return mobile;
	}
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	
	
	public TagObject getMemberIdentifier() {
		return memberIdentifier;
	}
	public void setMemberIdentifier(TagObject memberIdentifier) {
		this.memberIdentifier = memberIdentifier;
	}
	
	public String getJanrainAccountStatus() {
		return janrainAccountStatus;
	}
	public void setJanrainAccountStatus(String janrainAccountStatus) {
		this.janrainAccountStatus = janrainAccountStatus;
	}
	
	public String getBirthDate() {
		return birthDate;
	}
	public void setBirthDate(String birthDate) {
		this.birthDate = birthDate;
	}
	public String getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}
	public String getJanrainUUID() {
		return janrainUUID;
	}
	public void setJanrainUUID(String janrainUUID) {
		this.janrainUUID = janrainUUID;
	}
	
	public String getHouseHoldId() {
		return houseHoldId;
	}
	public void setHouseHoldId(String houseHoldId) {
		this.houseHoldId = houseHoldId;
	}
	public TagObject getSocialDomain() {
		return socialDomain;
	}
	public void setSocialDomain(TagObject socialDomain) {
		this.socialDomain = socialDomain;
	}
	public String getState() {
		return state;
	}
	public void setState(String state) {
		this.state = state;
	}
	

}
