package com.ko.cds.request.csr;

import java.io.Serializable;
import java.math.BigInteger;

import net.sf.oval.constraint.MaxLength;
import net.sf.oval.constraint.NotNull;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.codehaus.jackson.map.annotate.JsonDeserialize;

import com.ko.cds.utils.CustomTimestampDeserializer;
/**
 * This class is used to hold JSON structure converted into POJO for
 * CSR Ticket Post history request
 * @author ibm
 *
 */
@JsonIgnoreProperties(value = { "sessionId"})
public class CSRTicketPostRequest implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7315612277288879433L;
	/**Unique session ID created by TCCC and used for fraud service searches*/
	@MaxLength(value = 36, message = "ticket.create.violation")
	private String sessionUUID;
	
	/** Unique Id for the member generated by CDS*/
	@NotNull
	private BigInteger memberId;
	
	/**The Ko member’s Ko ID */
	@NotNull
	@MaxLength(value = 50, message = "ticket.create.violation")
	private String koMemberKoId;
	
	/** he KO team member’s name*/
	@NotNull
	@MaxLength(value = 250, message = "ticket.create.violation")
	private String koMemberName;
	
	/** The type of transaction - No referential integrity (example: Member Profile, Points Adjustment, Delete Member) */
	@NotNull
	@MaxLength(value = 50, message = "ticket.create.violation")
	private String dataType;
	
	/** The csr Reason code - No referential integrity */
	@NotNull
	@MaxLength(value = 150, message = "ticket.create.violation")
	private String csrReasonCode;
	
	/** The time of the transaction */
	@NotNull
	@JsonDeserialize(using = CustomTimestampDeserializer.class)
	private String timestamp;
	
	/** The clientTransactionId for possible matching with points transaction in the future */
	@NotNull
	@MaxLength(value = 36, message = "ticket.create.violation")
	private String clientTransactionId;
	
	/** It is used in service layer to hold sessionId mapped by session UUID and will not be shown in response*/
	private BigInteger sessionId;
	
	public BigInteger getSessionId() {
		return sessionId;
	}
	public void setSessionId(BigInteger sessionId) {
		this.sessionId = sessionId;
	}
	public String getSessionUUID() {
		return sessionUUID;
	}
	public void setSessionUUID(String sessionUUID) {
		this.sessionUUID = sessionUUID;
	}
	public BigInteger getMemberId() {
		return memberId;
	}
	public void setMemberId(BigInteger memberId) {
		this.memberId = memberId;
	}
	public String getKoMemberKoId() {
		return koMemberKoId;
	}
	public void setKoMemberKoId(String koMemberKoId) {
		this.koMemberKoId = koMemberKoId;
	}
	public String getKoMemberName() {
		return koMemberName;
	}
	public void setKoMemberName(String koMemberName) {
		this.koMemberName = koMemberName;
	}
	public String getDataType() {
		return dataType;
	}
	public void setDataType(String dataType) {
		this.dataType = dataType;
	}
	public String getCsrReasonCode() {
		return csrReasonCode;
	}
	public void setCsrReasonCode(String csrReasonCode) {
		this.csrReasonCode = csrReasonCode;
	}
	public String getTimestamp() {
		return timestamp;
	}
	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}
	public String getClientTransactionId() {
		return clientTransactionId;
	}
	public void setClientTransactionId(String clientTransactionId) {
		this.clientTransactionId = clientTransactionId;
	}
	
	

}
